<a href="https://colab.research.google.com/github/varnitjain8822/MACHINE-LEARNING-PROJECTS/blob/main/iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
x=df.drop('species',axis=1)
y=df['species']

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
model_knn=KNeighborsClassifier()
model_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [12]:
model_knn.score(x_test,y_test)

1.0

In [14]:
from sklearn.svm import SVC
model_svm=SVC(C=30,gamma='auto',kernel='rbf')
model_svm.fit(x_train,y_train)

SVC(C=30, gamma='auto')

In [15]:
model_svm.score(x_test,y_test)

1.0

In [19]:
from sklearn.model_selection import GridSearchCV
classifier=GridSearchCV(estimator=model_svm, param_grid={'C':[10,20,30],'kernel':['rbf','linear']}, cv=5,return_train_score=False)
classifier.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [10, 20, 30], 'kernel': ['rbf', 'linear']})

In [20]:
classifier.cv_results_

{'mean_fit_time': array([0.00449338, 0.00567002, 0.00723572, 0.00355959, 0.00429249,
        0.00336781]),
 'std_fit_time': array([1.63741318e-03, 2.52763453e-03, 3.20455552e-03, 1.38998727e-04,
        8.85908569e-04, 9.96331359e-05]),
 'mean_score_time': array([0.00279851, 0.00439086, 0.00480433, 0.00286331, 0.00270486,
        0.00259676]),
 'std_score_time': array([1.90011584e-04, 1.99557292e-03, 1.44757372e-03, 3.71691081e-04,
        8.13518291e-05, 4.33383335e-05]),
 'param_C': masked_array(data=[10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([1.        , 1.        , 0.95833333, 0.95833333, 0.95833333,
        0.95833333]),
 'split1_test_score': array([0.95833333, 0.95833333, 0.95833333, 0.95833333, 0.95833333,
        0.95833333]),
 'split2_test_score': array([0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
        0.83333333]),
 'split3_test_score': array([1.        , 0.95833333, 1.        , 1.        , 1.        ,
        0.95833333]),
 'split4_test_score': array([1.        , 1.        , 1.        , 1.        , 0.95833333,
        1.        ]),
 'mean_test_score': array([0.95833333, 0.95      , 0.95      , 0.95      , 0.94166667,
        0.94166667]),
 'std_test_score': array([0.06454972, 0.06123724, 0.06123724, 0.06123724, 0.05651942,
        0.05651942]),
 'rank_test_score': array([1, 2, 2, 2, 6, 5], dtype=int32)}

In [23]:
df=pd.DataFrame(classifier.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004493,0.001637,0.002799,0.000190,10,rbf,"{'C': 10, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1
1,0.005670,0.002528,0.004391,0.001996,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,2
2,0.007236,0.003205,0.004804,0.001448,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,2
3,0.003560,0.000139,0.002863,0.000372,20,linear,"{'C': 20, 'kernel': 'linear'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,2
4,0.004292,0.000886,0.002705,0.000081,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,0.958333,0.941667,0.056519,6
5,0.003368,0.000100,0.002597,0.000043,30,linear,"{'C': 30, 'kernel': 'linear'}",0.958333,0.958333,0.833333,0.958333,1.000000,0.941667,0.056519,5

In [24]:
from sklearn.model_selection import RandomizedSearchCV
classifier=RandomizedSearchCV(model_svm, {'C':[10,20,30],'kernel':['rbf','linear']}, cv=5,return_train_score=False)
classifier.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
                   param_distributions={'C': [10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [25]:
df=pd.DataFrame(classifier.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002589,0.000749,0.001817,0.000370,rbf,10,"{'kernel': 'rbf', 'C': 10}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1
1,0.002040,0.000048,0.001637,0.000152,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,2
2,0.002208,0.000115,0.001762,0.000323,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,2
3,0.002080,0.000104,0.001661,0.000109,linear,20,"{'kernel': 'linear', 'C': 20}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,2
4,0.002126,0.000068,0.001790,0.000206,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.958333,0.958333,0.833333,1.000000,0.958333,0.941667,0.056519,6
5,0.002056,0.000066,0.001610,0.000038,linear,30,"{'kernel': 'linear', 'C': 30}",0.958333,0.958333,0.833333,0.958333,1.000000,0.941667,0.056519,5

In [27]:
df[['param_kernel','param_C','mean_test_score']]

  param_kernel  param_C  mean_test_score
0          rbf       10         0.958333
1       linear       10         0.950000
2          rbf       20         0.950000
3       linear       20         0.950000
4          rbf       30         0.941667
5       linear       30         0.941667